name: MYSQL backup Rclone

on:
#  push:
#    branches:
#      - master
  schedule:
    - cron: 0 22 * * *
  workflow_dispatch:
    inputs:

jobs:
  backup:
    runs-on: ubuntu-latest
    name: mysql backup

    steps:
      - uses: actions/checkout@v2
      - name: MYSQLdump Install
        run: |
          sudo apt-get -y update
          sudo apt-get -y install mysql-client
          echo "BACKUP_DST=~/mysql/db_back" >> $GITHUB_ENV
          echo "NOW=$(date +"%Y.%m.%d")" >> $GITHUB_ENV
          echo "OLD=$(date -d -5day +"%Y.%m.%d")" >> $GITHUB_ENV

      - name: MYSQLdump Run
        run: |
          mkdir -p ${{ env.BACKUP_DST }}
          mysqldump --no-tablespaces --ssl-mode DISABLED -u${{ secrets.DB_USER }} -p${{ secrets.DB_PSW }} -h ${{ secrets.DB_HOST }} -P ${{ secrets.DB_PORT }} --databases ${{ secrets.DB_NAME }} | gzip > ${{ env.BACKUP_DST }}/${{ secrets.DB_NAME }}${{ env.NOW }}.sql.gz
        
      - name: Rclone Install
        run: curl https://rclone.org/install.sh | sudo bash
        
      - name: Rclone Config
        run: |
          mkdir -p ~/.config/rclone/
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.RCLONE_CONFIG }}
          EOF
      - name: Rclone Run
        run: |
          rclone copy ${{ env.BACKUP_DST }} ${{ secrets.BACKUP_DEST }} --include "${{ secrets.DB_NAME }}${{ env.NOW }}.sql.gz"
          rclone delete ${{ secrets.BACKUP_DEST }} --include "${{ secrets.DB_NAME }}${{ env.OLD }}.sql.gz"
          echo "备份完成"
