name: gclone sync

on:
#  push:
#    branches:
#      - master
  schedule:
    - cron: 0 */6 * * *
  workflow_dispatch:
    inputs:
    
jobs:
  sync:
    runs-on: ubuntu-latest
    name: GD sync by gclone

    steps:
      - uses: actions/checkout@v2
      - name: gclone Install
        run: curl https://git.io/gclone.sh | sudo bash
        
      - name: gclone Config
        run: |
          cp /usr/bin/gclone /usr/bin/rclone
          mkdir -p ~/.config/rclone/sa && cd ~/.config/rclone/sa
          curl -L "${{ secrets.GCLONE_SA_DLURL }}" -o accounts.zip
          unzip -jq -o accounts.zip
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.GCLONE_CONFIG }}
          EOF

      - name: gclone Run
        run: |
          rclone sync ${{ secrets.SOURCE_DEST }} --drive-server-side-across-configs --transfers 16 --checkers 32 --checksum --stats-one-line-date -q
          echo "同步完成"

