name: test
on:
  workflow_dispatch:
    inputs:
    
jobs:
  my_job:
    runs-on: ubuntu-latest
    name: test

    steps:
      - uses: actions/checkout@v2

      - name: gclone Config
        run: |
          mkdir -p ~/.config/rclone/sa && cd ~/.config/rclone/sa
          curl -L "${{ secrets.GCLONE_SA_DLURL }}" -o accounts.zip
          unzip -jq -o accounts.zip
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.GCLONE_CONFIG }}
          EOF

      - name: gclone Run
        run: |
          rclone sync ${{ secrets.SOURCE_DEST }} --drive-server-side-across-configs --transfers 16 --checkers 32 --checksum --stats-one-line-date -q
          echo "同步完成"
