name: test
on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
    
jobs:
  my_job:
    runs-on: ubuntu-latest
    name: test

    steps:
      - uses: actions/checkout@v2
      - name: gclone Install
        run: |
          wget -qO- https://api.github.com/repos/donwa/gclone/releases/latest \
          | grep browser_download_url | grep Linux_x86_64 | cut -d '"' -f 4 \
          | wget --no-verbose -i- -O- | gzip -d -c > rclone
          sudo mv rclone /usr/bin
          sudo chmod +x /usr/bin/rclone

      - name: gclone Config
        run: |
          mkdir -p ~/.config/rclone/sa && cd ~/.config/rclone/sa
          curl -L "${{ secrets.GCLONE_SA_DLURL }}" -o accounts.zip
          unzip -jq -o accounts.zip
          ls
          cat >  ~/.config/rclone/rclone.conf  << EOF
          ${{ secrets.GCLONE_CONFIG }}
          EOF

      - name: gclone Run
        run: |
          rclone sync ${{ secrets.GCLONE_PATCH }} --drive-server-side-across-configs --transfers 16 --checkers 32 --checksum --stats-one-line-date -q
          echo "同步完成"
